baseurl = "/"
languageCode = "en-us"
title = "Britt's Bits & Bytes"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Adventures in data."
  cover = "images/dol_nuv.JPG"
  author = "Brittany Bowers"
  authorlocation = "San Francisco, USA"
  authorwebsite = "http://brittanybowers.com"
  bio= "my bio"
  logo = "images/home-outline.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "brittbowers"
  #twitterName = "vjeantet"
  # facebookName = ""
  linkedinName = "Brittany Bowers"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
